version: '3.7'

services:
  automatech-api:
    image: automatech-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - typebotnet
    volumes:
      - /var/www/Automatech_api_Watts/sessions:/app/sessions
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.automatech_api.rule=Host(`api.wattsapi.automatech.tech`)
        - traefik.http.routers.automatech_api.entrypoints=websecure
        - traefik.http.routers.automatech_api.tls.certresolver=letsencryptresolver
        - traefik.http.routers.automatech_api.service=automatech_api
        - traefik.http.services.automatech_api.loadbalancer.server.port=3003
        - traefik.http.services.automatech_api.loadbalancer.passHostHeader=1

  automatech-dashboard:
    image: automatech-dashboard:latest
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    networks:
      - typebotnet
    depends_on:
      - automatech-api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.automatech_dashboard.rule=Host(`wattsapi.automatech.tech`)
        - traefik.http.routers.automatech_dashboard.entrypoints=websecure
        - traefik.http.routers.automatech_dashboard.tls.certresolver=letsencryptresolver
        - traefik.http.routers.automatech_dashboard.service=automatech_dashboard
        - traefik.http.services.automatech_dashboard.loadbalancer.server.port=80
        - traefik.http.services.automatech_dashboard.loadbalancer.passHostHeader=1

networks:
  typebotnet:
    external: true
    name: typebotnet

volumes:
  sessions:
