version: '3.8'

services:
  automatech-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automatech-api
    restart: unless-stopped
    ports:
      - "3003:3003"
    volumes:
      - ./sessions:/app/sessions
    environment:
      - NODE_ENV=production
    networks:
      - automatech-network
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.automatech-api.rule=Host(`api.wattsapi.automatech.tech`)"
        - "traefik.http.routers.automatech-api.entrypoints=websecure"
        - "traefik.http.routers.automatech-api.tls.certresolver=letspre"
        - "traefik.http.services.automatech-api.loadbalancer.server.port=3003"

  automatech-dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: automatech-dashboard
    restart: unless-stopped
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.automatech-dashboard.rule=Host(`wattsapi.automatech.tech`)"
        - "traefik.http.routers.automatech-dashboard.entrypoints=websecure"
        - "traefik.http.routers.automatech-dashboard.tls.certresolver=letspre"
        - "traefik.http.services.automatech-dashboard.loadbalancer.server.port=80"
    depends_on:
      - automatech-api
    networks:
      - automatech-network
      - traefik-public

networks:
  automatech-network:
    driver: bridge
  traefik-public:
    external: true

volumes:
  sessions:
